version: 2

defaults: &defaults

jobs:
  build:
    context: docker-hub-credentials
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout

      - run: yarn
      - run: yarn build

workflows:
  version: 2
  build:
    jobs:
      - build
