version: 2

defaults: &defaults

jobs:
  build:
    context: docker-hub-credentials
    docker:
      - image: circleci/node:16
    working_directory: ~/repo
    steps:
      - checkout

      - run: yarn
      - run: yarn build
      - run: yarn lint

      - persist_to_workspace:
          root: '..'
          paths: 
            - repo
            - .ssh

  push:
    docker:
      - image: circleci/node:16
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      # Push website
      - run: bash .circleci/scripts/deploy-ghpages.sh

workflows:
  version: 2
  build:
    jobs:
      - build
      - push:
          filters:
            branches:
              only:
                - master
          requires:
            - build